name: Validación de script .sh

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instalar ShellCheck
        run: sudo apt-get install shellcheck

      - name: Validar script.sh con ShellCheck
        run: shellcheck script.sh
